website_index:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }

website_sophrologie:
    path:     /sophrologie
    defaults: { _controller: WebsiteBundle:Website:sophrologie }

website_sophrologie_individuel:
    path:     /sophrologie/seances_individuelles
    defaults: { _controller: WebsiteBundle:Website:sophrologieIndividuel }

website_sophrologie_groupe:
    path:     /sophrologie/seances_en_groupe
    defaults: { _controller: WebsiteBundle:Website:sophrologieGroupe }

website_sophrologie_ateliers_stages:
    path:     /sophrologie/ateliers_et_stages
    defaults: { _controller: WebsiteBundle:Website:sophrologieAteliersStages }

website_actualites:
    path:     /sophrologie/ateliers_et_stages/actualites/{id}
    defaults: { _controller: WebsiteBundle:Website:actualites }
    requirements:
        id: \d+

website_soins_energetiques:
    path:     /soins_energetiques
    defaults: { _controller: WebsiteBundle:Website:soinsEnergetiques }

website_soins_energetiques_therapies:
    path:     /soins_energetiques/auratherapie_magnetisme
    defaults: { _controller: WebsiteBundle:Website:soinsAuratherapieMagnetisme }

website_soins_energetiques_chamaniques:
    path:     /soins_energetiques/soins_chamaniques
    defaults: { _controller: WebsiteBundle:Website:soinsChamaniques }

website_qui_suis_je:
    path:     /qui_suis_je
    defaults: { _controller: WebsiteBundle:Website:quiSuisJe }

website_qui_ma_pratique:
    path:     /qui_suis_je/ma_pratique
    defaults: { _controller: WebsiteBundle:Website:quiMaPratique }

website_bibliographie:
    path:     /bibliographie
    defaults: { _controller: WebsiteBundle:Website:bibliographie }

website_biblio_medias:
    path:     /bibliographie/medias
    defaults: { _controller: WebsiteBundle:Website:biblioMedias }

website_contact:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:contact }

website_contact_rdv:
    path:     /prendre_un_rdv
    defaults: { _controller: WebsiteBundle:Website:contactRDV }
