website_index:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }

website_sophrologie:
    path:     /sophrologie
    defaults: { _controller: WebsiteBundle:Website:sophrologie }
    
website_sophrologie_deroulement_seance:
    path:     /sophrologie/deroulement_seance
    defaults: { _controller: WebsiteBundle:Website:sophrologieDeroulementSeance }

website_sophrologie_groupe:
    path:     /sophrologie/groupe
    defaults: { _controller: WebsiteBundle:Website:sophrologieGroupe }

website_sophrologie_individuel:
    path:     /sophrologie/individuel
    defaults: { _controller: WebsiteBundle:Website:sophrologieIndividuel }

website_sophrologie_ateliers_stages:
    path:     /sophrologie/ateliers_stages
    defaults: { _controller: WebsiteBundle:Website:sophrologieAteliersStages }

website_soins_energetiques:
    path:     /soins_energetiques
    defaults: { _controller: WebsiteBundle:Website:soinsEnergetiques }

website_qui_suis_je:
    path:     /qui_suis_je
    defaults: { _controller: WebsiteBundle:Website:quiSuisJe }

website_bibliographie:
    path:     /bibliographie
    defaults: { _controller: WebsiteBundle:Website:bibliographie }

website_tarifs:
    path:     /tarifs
    defaults: { _controller: WebsiteBundle:Website:tarifs }

website_contact:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:contact }
