website_index:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }

website_sophrologie:
    path:     /sophrologie
    defaults: { _controller: WebsiteBundle:Website:sophrologie }

website_sophrologie_individuel:
    path:     /sophrologie/seances_individuelles
    defaults: { _controller: WebsiteBundle:Website:sophrologieIndividuel }

website_sophrologie_groupe:
    path:     /sophrologie/seances_de_groupe
    defaults: { _controller: WebsiteBundle:Website:sophrologieGroupe }

website_sophrologie_ateliers_stages:
    path:     /sophrologie/ateliers_et_stages
    defaults: { _controller: WebsiteBundle:Website:sophrologieAteliersStages }

website_soins_energetiques:
    path:     /soins_energetiques
    defaults: { _controller: WebsiteBundle:Website:soinsEnergetiques }

website_qui_suis_je:
    path:     /qui_suis_je
    defaults: { _controller: WebsiteBundle:Website:quiSuisJe }

website_bibliographie:
    path:     /bibliographie
    defaults: { _controller: WebsiteBundle:Website:bibliographie }

website_contact:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:contact }
