<?php

namespace AdminBundle\Repository;

/**
 * AddressOtherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressOtherRepository extends \Doctrine\ORM\EntityRepository
{
}
