<?php

namespace AdminBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertsAddress(\Datetime $date, $id) 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')->addSelect('i')
            ->leftJoin('a.pdf', 'p')->addSelect('p')
            ->leftJoin('a.address', 'ad')->addSelect('ad')
            ->leftJoin('a.addressOther', 'ado')->addSelect('ado')
            ->where('a.date >= :date')
            ->setParameter('date', $date)
            ->andWhere('ad.id = :id')
            ->setParameter('id', $id)
            ->orderBy('a.date', 'ASC')
            ->getQuery()
        ;
        
        return $query->getResult();
    }
}
